Henso_Event = {}


--//Anti Jail//--
Henso_Event.AntiJaillAll = true -- Your jail Event needs to be esx-qalle-jail:jailPlayer
Henso_Event.AntiJaillAllKick = false  -- Anti Jail All (Kick)
Henso_Event.AntiJaillAllBan = true  -- Anti Jail All (Ban)


--//Anti Blacklisted Events//--
Henso_Event.BlacklistedEvents = true  -- Anti Blacklist Events 
Henso_Event.BlacklistedEventsKick = true  -- Anti Blacklist Events (Kick)
Henso_Event.BlacklistedEventsBan = true  -- Anti Blacklist Events (Ban)


--//Anti Trigger Spam//--
Henso_Event.AntiSpamTrigger = true  -- Anti Spawn Trigger Events


--//Anti Community Service All//--
Henso_Event.AntiCommunityServiceAll = true -- Your CommunityService Event needs to be 'esx_communityservice:sendToCommunityService
Henso_Event.AntiCommunityServiceAllKick = true  -- Anti Community Event All (Kick)
Henso_Event.AntiCommunityServiceAllBan = true  -- Anti Community Event All (Ban)


--//Anti DpEmote All//--
Henso_Event.AntiDpemoteAll = true  -- Anti Dpemotes All
Henso_Event.AntiDpemoteAllKick = false  -- Anti Dpemotes All (Kick)
Henso_Event.AntiDpemoteAllBan = true  -- Anti Dpemotes All (Ban)


--//Blacklisted Events//--
Henso_Event.BlacklistedEventsList = { -- There you can add blacklisted triggers
    'bringplayertome'
}


--//Secured Events//--
Henso_Event.SecuredJobEvents = {
    { eventName = "esx_billing:sendBill", job = "police", "sheriff", "fbi", "ambulance", "mechanic",},
    { eventName = "esx_ambulancejob:revive", job = "ambulance" ,}, -- You can add more Events for Jobs
    { eventName = "esx_truckerjob:pay", job = "trucker",},
    { eventName = "esx_policejob:handcuff", job = "police", "sheriff", "fbi",},
}


--//Max Valued Events//--
Henso_Event.MaxValuedEvents = { -- You have to be careful here, you have to adjust the events according to your scripts, wich is the maximum number of you script. There is a lot of good shit xD
	["esx_society:billing"] = {maxvalue=9999999999},                               
    ["fuel:pay"] = {maxvalue=999999999999},
    ["skinchanger:openSaveableMenu"] = {maxvalue=10},
    ["ambulancier:selfRespawn"] = {maxvalue=2},
    ["bank:transfer"] = {maxvalue=99999999999999},
    ["esx-qalle-jail:openJailMenu"] = {maxvalue=2},
    ["esx_jailer:wysylandoo"] = {maxvalue=2},
    ["esx_policejob:getarrested"] = {maxvalue=2},
    ["esx_society:openBossMenu"] = {maxvalue=2},
    ["esx:spawnVehicle"] = {maxvalue=2},
    ["esx_status:set"] = {maxvalue=10},
    ["HCheat:TempDisableDetection"] = {maxvalue=1},
    ["UnJP"] = {maxvalue=2},
    ["8321hiue89js"] = {maxvalue=10},
    ["adminmenu:allowall"] = {maxvalue=10},
    ["AdminMenu:giveBank"] = {maxvalue=999999999},
    ["AdminMenu:giveCash"] = {maxvalue=999999999},
    ["AdminMenu:giveDirtyMoney"] = {maxvalue=999999999},
    ["Tem2LPs5Para5dCyjuHm87y2catFkMpV"] = {maxvalue=10},
    ["dqd36JWLRC72k8FDttZ5adUKwvwq9n9m"] = {maxvalue=10},
    ["antilynx8:anticheat"] = {maxvalue=10},
    ["antilynxr4:detect"] = {maxvalue=10},
    ["antilynxr6:detection"] = {maxvalue=10},
    ["ynx8:anticheat"] = {maxvalue=10},
    ["antilynx8r4a:anticheat"] = {maxvalue=10},
    ["lynx8:anticheat"] = {maxvalue=10},
    ["AntiLynxR4:kick"] = {maxvalue=10},
    ["AntiLynxR4:log"] = {maxvalue=10},
    ["bank:deposit"] = {maxvalue=10},
    ["bank:withdraw"] = {maxvalue=10},
    ["Banca:deposit"] = {maxvalue=10},
    ["Banca:withdraw"] = {maxvalue=10},
    ["BsCuff:Cuff696999"] = {maxvalue=10},
    ["CheckHandcuff"] = {maxvalue=10},
    ["cuffServer"] = {maxvalue=10},
    ["cuffGranted"] = {maxvalue=10},
    ["DiscordBot:playerDied"] = {maxvalue=10},
    ["DFWM:adminmenuenable"] = {maxvalue=10},
    ["DFWM:askAwake"] = {maxvalue=10},
    ["DFWM:checkup"] = {maxvalue=10},
    ["DFWM:cleanareaentity"] = {maxvalue=10},
    ["DFWM:cleanareapeds"] = {maxvalue=10},
    ["DFWM:cleanareaveh"] = {maxvalue=10},
    ["DFWM:enable"] = {maxvalue=10},
    ["DFWM:invalid"] = {maxvalue=10},
    ["DFWM:log"] = {maxvalue=10},
    ["DFWM:openmenu"] = {maxvalue= 2},
    ["DFWM:spectate"] = {maxvalue=10},
    ["DFWM:ViolationDetected"] = {maxvalue=10},
    ["dmv:success"] = {maxvalue=10},
    ["eden_garage:payhealth"] = {maxvalue=10},
    ["ems:revive"] = {maxvalue=5},
    ["esx_ambulancejob:revive"] = {maxvalue=5},
    ["esx_billing:sendBill"] = {maxvalue=99999999999},
    ["esx_banksecurity:pay"] = {maxvalue=10},
    ["esx_blanchisseur:startWhitening"] = {maxvalue=10},
    ["esx_carthief:alertcops"] = {maxvalue=10},
    ["esx_carthief:pay"] = {maxvalue=10},
    ["esx_dmvschool:addLicense"] = {maxvalue=10},
    ["esx_dmvschool:pay"] = {maxvalue=50000},
    ["esx_drugs:startHarvestWeed"] = {maxvalue=10},
    ["esx_drugs:startTransformWeed"] = {maxvalue=10},
    ["esx_drugs:startSellWeed"] = {maxvalue=10},
    ["esx_drugs:startHarvestCoke"] = {maxvalue=10},
    ["esx_drugs:startTransformCoke"] = {maxvalue=10},
    ["esx_drugs:startSellCoke"] = {maxvalue=10},
    ["esx_drugs:startHarvestMeth"] = {maxvalue=10},
    ["esx_drugs:startTransformMeth"] = {maxvalue=10},
    ["esx_drugs:startSellMeth"] = {maxvalue=10},
    ["esx_drugs:startHarvestOpium"] = {maxvalue=10},
    ["esx_drugs:startTransformOpium"] = {maxvalue=10},
    ["esx_drugs:startSellOpium"] = {maxvalue=10},
    ["esx_drugs:stopHarvestCoke"] = {maxvalue=10},
    ["esx_drugs:stopTransformCoke"] = {maxvalue=10},
    ["esx_drugs:stopSellCoke"] = {maxvalue=10},
    ["esx_drugs:stopHarvestMeth"] = {maxvalue=10},
    ["esx_drugs:stopTransformMeth"] = {maxvalue=10},
    ["esx_drugs:stopSellMeth"] = {maxvalue=10},
    ["esx_drugs:stopHarvestWeed"] = {maxvalue=10},
    ["esx_drugs:stopTransformWeed"] = {maxvalue=10},
    ["esx_drugs:stopSellWeed"] = {maxvalue=10},
    ["esx_drugs:stopHarvestOpium"] = {maxvalue=10},
    ["esx_drugs:stopTransformOpium"] = {maxvalue=10},
    ["esx_drugs:stopSellOpium"] = {maxvalue=10},
    ["esx:enterpolicecar"] = {maxvalue=10},
    ["esx_fueldelivery:pay"] = {maxvalue=10},
    ["esx:giveInventoryItem"] = {maxvalue=10},
    ["esx_garbagejob:pay"] = {maxvalue=10},
    ["esx_godirtyjob:pay"] = {maxvalue=10},
    ["esx_gopostaljob:pay"] = {maxvalue=10},
    ["esx_handcuffs:cuffing"] = {maxvalue=10},
    ["esx_jail:sendToJail"] = {maxvalue=10},
    ["esx_jail:unjailQuest"] = {maxvalue=10},
    ["esx_jailer:sendToJail"] = {maxvalue=10},
    ["esx_jailer:unjailTime"] = {maxvalue=10},
    ["esx_jobs:caution"] = {maxvalue=10},
    ["esx_mecanojob:onNPCJobCompleted"] = {maxvalue=10},
    ["esx_mechanicjob:startHarvest"] = {maxvalue=10},
    ["esx_mechanicjob:startCraft"] = {maxvalue=10},
    ["esx_pizza:pay"] = {maxvalue=10},
    ["esx_policejob:handcuff"] = {maxvalue=10},
    ["esx_policejob:requestarrest"] = {maxvalue=10},
    ["esx-qalle-jail:jailPlayer"] = {maxvalue=10},
    ["esx-qalle-jail:jailPlayerNew"] = {maxvalue=10},
    ["esx-qalle-hunting:reward"] = {maxvalue=10},
    ["esx-qalle-hunting:sell"] = {maxvalue=10},
    ["esx_ranger:pay"] = {maxvalue=10},
    ["esx:removeInventoryItem"] = {maxvalue=5},
    ["esx_truckerjob:pay"] = {maxvalue=10},
    ["esx_skin:responseSaveSkin"] = {maxvalue=10},
    ["esx_slotmachine:sv:2"] = {maxvalue=10},
    ["esx_society:getOnlinePlayers"] = {maxvalue=10},
    ["esx_society:setJob"] = {maxvalue=10},
    ["esx_vehicleshop:setVehicleOwned"] = {maxvalue=10},
    ["hentailover:xdlol"] = {maxvalue=10},
    ["JailUpdate"] = {maxvalue=10},
    ["js:jailuser"] = {maxvalue=10},
    ["js:removejailtime"] = {maxvalue=10},
    ["LegacyFuel:PayFuel"] = {maxvalue=10},
    ["ljail:jailplayer"] = {maxvalue=10},
    ["lscustoms:payGarage"] = {maxvalue=10},
    ["mellotrainer:adminTempBan"] = {maxvalue=10},
    ["mellotrainer:adminKick"] = {maxvalue=10},
    ["mellotrainer:s_adminKill"] = {maxvalue=10},
    ["NB:destituerplayer"] = {maxvalue=10},
    ["NB:recruterplayer"] = {maxvalue=10},
    ["OG_cuffs:cuffCheckNearest"] = {maxvalue=10},
    ["paramedic:revive"] = {maxvalue=10},
    ["police:cuffGranted"] = {maxvalue=10},
    ["unCuffServer"] = {maxvalue=10},
    ["uncuffGranted"] = {maxvalue=10},
    ["vrp_slotmachine:server:2"] = {maxvalue=10},
    ["whoapd:revive"] = {maxvalue=10},
    ["gcPhone:_internalAddMessageDFWM"] = {maxvalue=10},
    ["gcPhone:tchat_channelDFWM"] = {maxvalue=10},
    ["esx_vehicleshop:setVehicleOwnedDFWM"] = {maxvalue=10},
    ["esx_mafiajob:confiscateDFWMPlayerItem"] = {maxvalue=10},
    ["_chat:messageEntDFWMered"] = {maxvalue=10},
    ["lscustoms:pDFWMayGarage"] = {maxvalue=10},
    ["vrp_slotmachDFWMine:server:2"] = {maxvalue=10},
    ["Banca:dDFWMeposit"] = {maxvalue=10},
    ["bank:depDFWMosit"] = {maxvalue=10},
    ["give_back"] = {maxvalue=10},
    ["esx_fueldDFWMelivery:pay"] = {maxvalue=10},
    ["esx_carthDFWMief:pay"] = {maxvalue=10},
    ["esx_godiDFWMrtyjob:pay"] = {maxvalue=10},
    ["esx_pizza:pDFWMay"] = {maxvalue=10},
    ["esx_ranger:pDFWMay"] = {maxvalue=10},
    ["esx_garbageDFWMjob:pay"] = {maxvalue=10},
    ["esx_truckDFWMerjob:pay"] = {maxvalue=10},
    ["AdminMeDFWMnu:giveBank"] = {maxvalue=10},
    ["AdminMDFWMenu:giveCash"] = {maxvalue=10},
    ["esx_goDFWMpostaljob:pay"] = {maxvalue=10},
    ["esx_baDFWMnksecurity:pay"] = {maxvalue=10},
    ["esx_sloDFWMtmachine:sv:2"] = {maxvalue=10},
    ["esx:giDFWMveInventoryItem"] = {maxvalue=10},
    ["NB:recDFWMruterplayer"] = {maxvalue=10},
    ["esx_biDFWMlling:sendBill"] = {maxvalue=10},
    ["esx_jDFWMailer:sendToJail"] = {maxvalue=10},
    ["esx_jaDFWMil:sendToJail"] = {maxvalue=10},
    ["esx-qalle-jail:jailPDFWMlayer"] = {maxvalue=10},
    ["esx_dmvschool:pDFWMay"] = {maxvalue=10},
    ["LegacyFuel:PayFuDFWMel"] = {maxvalue=10},
    ["OG_cuffs:cuffCheckNeDFWMarest"] = {maxvalue=10},
    ["CheckHandcDFWMuff"] = {maxvalue=10},
    ["cuffSeDFWMrver"] = {maxvalue=10},
    ["cuffGDFWMranted"] = {maxvalue=10},
    ["police:cuffGDFWMranted"] = {maxvalue=10},
    ["esx_handcuffs:cufDFWMfing"] = {maxvalue=10},
    ["esx_policejob:haDFWMndcuff"] = {maxvalue=10},
    ["bank:withdDFWMraw"] = {maxvalue=10},
    ["dmv:succeDFWMss"] = {maxvalue=10},
    ["esx_skin:responseSaDFWMveSkin"] = {maxvalue=10},
    ["esx_dmvschool:addLiceDFWMnse"] = {maxvalue=10},
    ["esx_mechanicjob:starDFWMtCraft"] = {maxvalue=10},
    ["esx_drugs:startHarvestWDFWMeed"] = {maxvalue=10},
    ["esx_drugs:startTransfoDFWMrmWeed"] = {maxvalue=10},
    ["esx_drugs:startSellWeDFWMed"] = {maxvalue=10},
    ["esx_drugs:startHarvestDFWMCoke"] = {maxvalue=10},
    ["esx_drugs:startTransDFWMformCoke"] = {maxvalue=10},
    ["esx_drugs:startSellCDFWMoke"] = {maxvalue=10},
    ["esx_drugs:startHarDFWMvestMeth"] = {maxvalue=10},
    ["esx_drugs:startTDFWMransformMeth"] = {maxvalue=10},
    ["esx_drugs:startSellMDFWMeth"] = {maxvalue=10},
    ["esx_drugs:startHDFWMarvestOpium"] = {maxvalue=10},
    ["esx_drugs:startSellDFWMOpium"] = {maxvalue=10},
    ["esx_drugs:starDFWMtTransformOpium"] = {maxvalue=10},
    ["esx_blanchisDFWMseur:startWhitening"] = {maxvalue=10},
    ["esx_drugs:stopHarvDFWMestCoke"] = {maxvalue=10},
    ["esx_drugs:stopTranDFWMsformCoke"] = {maxvalue=10},
    ["esx_drugs:stopSellDFWMCoke"] = {maxvalue=10},
    ["esx_drugs:stopHarvesDFWMtMeth"] = {maxvalue=10},
    ["esx_drugs:stopTranDFWMsformMeth"] = {maxvalue=10},
    ["esx_drugs:stopSellMDFWMeth"] = {maxvalue=10},
    ["esx_drugs:stopHarDFWMvestWeed"] = {maxvalue=10},
    ["esx_drugs:stopTDFWMransformWeed"] = {maxvalue=10},
    ["esx_drugs:stopSellWDFWMeed"] = {maxvalue=10},
    ["esx_drugs:stopHarvestDFWMOpium"] = {maxvalue=10},
    ["esx_drugs:stopTransDFWMformOpium"] = {maxvalue=10},
    ["esx_drugs:stopSellOpiuDFWMm"] = {maxvalue=10},
    ["esx_society:openBosDFWMsMenu"] = {maxvalue=10},
    ["esx_jobs:caDFWMution"] = {maxvalue=10},
    ["esx_tankerjob:DFWMpay"] = {maxvalue=10},
    ["esx_vehicletrunk:givDFWMeDirty"] = {maxvalue=10},
    ["gambling:speDFWMnd"] = {maxvalue=10},
    ["AdminMenu:giveDirtyMDFWMoney"] = {maxvalue=10},
    ["esx_moneywash:depoDFWMsit"] = {maxvalue=10},
    ["esx_moneywash:witDFWMhdraw"] = {maxvalue=10},
    ["mission:completDFWMed"] = {maxvalue=10},
    ["truckerJob:succeDFWMss"] = {maxvalue=10},
    ["99kr-burglary:addMDFWMoney"] = {maxvalue=10},
    ["esx_jailer:unjailTiDFWMme"] = {maxvalue=10},
    ["esx_ambulancejob:reDFWMvive"] = {maxvalue=10},
    ["DiscordBot:plaDFWMyerDied"] = {maxvalue=10},
    ["esx:getShDFWMaredObjDFWMect"] = {maxvalue=10},
    ["esx_society:getOnlDFWMinePlayers"] = {maxvalue=10},
    ["js:jaDFWMiluser"] = {maxvalue=10},
    ["h:xd"] = {maxvalue=10},
    ["adminmenu:setsalary"] = {maxvalue=10},
    ["adminmenu:cashoutall"] = {maxvalue=10},
    ["bank:tranDFWMsfer"] = {maxvalue=10},
    ["paycheck:bonDFWMus"] = {maxvalue=10},
    ["paycheck:salDFWMary"] = {maxvalue=10},
    ["HCheat:TempDisableDetDFWMection"] = {maxvalue=10},
    ["esx_drugs:pickedUpCDFWMannabis"] = {maxvalue=10},
    ["esx_drugs:processCDFWMannabis"] = {maxvalue=10},
    ["esx-qalle-hunting:DFWMreward"] = {maxvalue=10},
    ["esx-qalle-hunting:seDFWMll"] = {maxvalue=10},
    ["esx_mecanojob:onNPCJobCDFWMompleted"] = {maxvalue=10},
    ["BsCuff:Cuff696DFWM999"] = {maxvalue=10},
    ["veh_SR:CheckMonDFWMeyForVeh"] = {maxvalue=10},
    ["esx_carthief:alertcoDFWMps"] = {maxvalue=10},
    ["mellotrainer:adminTeDFWMmpBan"] = {maxvalue=10},
    ["mellotrainer:adminKickDFWM"] = {maxvalue=10},
    ["esx_society:putVehicleDFWMInGarage"] = {maxvalue=10},
    ["cs_einreise:remeinreise"] = {maxvalue=10},
    ["ev:getPlateNui"] = {maxvalue=100}                        -- Do {maxvalue=-1} if you only will get banned on -1 trigger. Good for Police triggers ;D
}


--//Blacklisted Explosions//--
Explosion = {
    [0] =  { NAME = "Grenade",              Log = true,  Punishment = "false"  },
    [1] =  { NAME = "GrenadeLauncher",      Log = true,  Punishment = "BAN"  },
    [2] =  { NAME = "Stick Bomb",           Log = true,  Punishment = false  },
    [3] =  { NAME = "Molotov",              Log = true,  Punishment = "false"  },
    [4] =  { NAME = "Rocket",               Log = true,  Punishment = "false"  },
    [5] =  { NAME = "TankShell",            Log = true,  Punishment = "false"  },
    [6] =  { NAME = "Hi_Octane",            Log = true, Punishment = false  },
    [7] =  { NAME = "Car",                  Log = true, Punishment = false  },
    [8] =  { NAME = "Plance",               Log = true, Punishment = false  },
    [9] =  { NAME = "PetrolPump",           Log = true, Punishment = false  },
    [10] = { NAME = "Bike",                 Log = true, Punishment = false  },
    [11] = { NAME = "Dir_Steam",            Log = true, Punishment = false  },
    [12] = { NAME = "Dir_Flame",            Log = true, Punishment = false  },
    [13] = { NAME = "Dir_Water_Hydrant",    Log = true, Punishment = false  },
    [14] = { NAME = "Dir_Gas_Canister",     Log = true, Punishment = false  },
    [15] = { NAME = "Boat",                 Log = true, Punishment = false  },
    [16] = { NAME = "Ship_Destroy",         Log = true, Punishment = false  },
    [17] = { NAME = "Truck",                Log = true, Punishment = false  },
    [18] = { NAME = "Bullet",               Log = true,  Punishment = "false"  },
    [19] = { NAME = "SmokeGrenadeLauncher", Log = true,  Punishment = "false"  },
    [20] = { NAME = "SmokeGrenade",         Log = true, Punishment = false  },
    [21] = { NAME = "BZGAS",                Log = true, Punishment = false  },
    [22] = { NAME = "Flare",                Log = true, Punishment = false  },
    [23] = { NAME = "Gas_Canister",         Log = true, Punishment = false  },
    [24] = { NAME = "Extinguisher",         Log = true, Punishment = false  },
    [25] = { NAME = "Programmablear",       Log = true, Punishment = false  },
    [26] = { NAME = "Train",                Log = true, Punishment = false  },
    [27] = { NAME = "Barrel",               Log = true, Punishment = false  },
    [28] = { NAME = "PROPANE",              Log = true, Punishment = false  },
    [29] = { NAME = "Blimp",                Log = true, Punishment = false  },
    [30] = { NAME = "Dir_Flame_Explode",    Log = true, Punishment = false  },
    [31] = { NAME = "Tanker",               Log = true, Punishment = false  },
    [32] = { NAME = "PlaneRocket",          Log = true,  Punishment = "false"  },
    [33] = { NAME = "VehicleBullet",        Log = true, Punishment = false  },
    [34] = { NAME = "Gas_Tank",             Log = true,  Punishment = "WARN" },
    [35] = { NAME = "FireWork",             Log = true, Punishment = false  },
    [36] = { NAME = "SnowBall",             Log = true, Punishment = false  },
    [37] = { NAME = "Valkyrie_Cannon",      Log = true,  Punishment = "BAN"  },
    [38] = { NAME = "Railgun",              Log = true,  Punishment = "BAN"  }
}


--//Anti Spam Triggers//--
Henso_Event.AntiSpamTriggerList = { -- This can catch money spamming, or other shit, the anticheat will block it.
    { EVENT = "esx_policejob:handcuff",           MAX_TIME = 10  },
    { EVENT = "esx-qalle-hunting:reward",         MAX_TIME = 3  },
    { EVENT = "esx:giveInventoryItem",            MAX_TIME = 4  },
    { EVENT = "esx_billing:sendBill" ,            MAX_TIME = 10  },
    { EVENT = "esx_billing:sendBill" ,            MAX_TIME = 10  },
    { EVENT = "chatE3vent" ,                      MAX_TIME = 2  },
    { EVENT = "_chat:messageEntered3" ,           MAX_TIME = 2  },
    { EVENT = "playerDi3ed" ,                     MAX_TIME = 2  },
    { EVENT = "gcPhone:_internalAddMessage",      MAX_TIME = 4  },
    { EVENT = "gcPhone:tchat_channel",            MAX_TIME = 4  },
    { EVENT = "ServerValidEmote",                 MAX_TIME = 4  },
    { EVENT = "lester:vendita",                   MAX_TIME = 20 },
    { EVENT = "esx:confiscatePlayerItem",         MAX_TIME = 4  },
    { EVENT = "esx-qalle-jail:jailPlayer",         MAX_TIME = 1  },
    { EVENT = "esx_multicharacter:SetupCharacters", MAX_TIME = 1000000 },
    { EVENT = "esx:loadingScreenOff",         MAX_TIME = 1000000 },
    { EVENT = "skinchanger:loadSkin",         MAX_TIME = 1000000  },
    { EVENT = "esx_identity:showRegisterIdentity", MAX_TIME = 1000000 },
    { EVENT = "esx_skin:openSaveableMenu", MAX_TIME = 1000000},
    { EVENT = "esx:onPlayerSpawn", MAX_TIME = 1000000 },
    { EVENT = "playerSpawned",         MAX_TIME = 1000000 },
    { EVENT = "esx:restoreLoadout",         MAX_TIME = 1000000  },
    { EVENT = "esx_multicharacter:SetupCharacters", MAX_TIME = 1000000 },
    { EVENT = "esx_skin:resetFirstSpawn", MAX_TIME = 1000000},
    { EVENT = "ev:getPlate", MAX_TIME = 100},
    { EVENT = "esx_ambulancejob:getDeathStatus",         MAX_TIME = 100},
    { EVENT = "esx_ambulancejob:setDeathStatus",            MAX_TIME = 100},
    { EVENT = "esx_ambulancejob:heal" ,            MAX_TIME = 100 },
    { EVENT = "esx_ambulancejob:heal" ,            MAX_TIME = 100 },
    { EVENT = "esx_ambulancejob:onPlayerDistress" , MAX_TIME = 100 },
    { EVENT = "esx_ambulancejob:checkBalance" ,           MAX_TIME = 100 },
    { EVENT = "esx_ambulancejob:payFine" ,                     MAX_TIME = 100 },
    { EVENT = "esx_ambulancejob:setDeathStatus",      MAX_TIME = 100  },
    { EVENT = "esx_ambulancejob:removeItemsAfterRPDeath",            MAX_TIME = 100  },
    { EVENT = "esx_basicneeds:resetStatus",                 MAX_TIME = 100  },
    { EVENT = "esx:onPlayerSpawn",                   MAX_TIME = 100 },
    { EVENT = "esx:onPlayerSpawn",         MAX_TIME = 100  },
    { EVENT = "playerSpawned",         MAX_TIME = 100  },
    { EVENT = "esx_phone:addSpecialContact",         MAX_TIME = 100  },
    { EVENT = "esx_ambulancejob:setDeathStatus",         MAX_TIME = 100  },
}